# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bffbb6cbd63b819377a651cbd595893bc704f6aaeb9e0e5cd107ad482dd39a49dc0173fb500023beb9809238d424fc6f067de77bb56efa83b8b07b34ef569d5

test:
  secret_key_base: ccd626eede5df768be95055be80dca750a5ecf8297bbf56450da42e77676281ef0a9c9bc0cfce1a97bce7d31545a54b6b600b1ac9667e67b407034cde9293c6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
